import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships the Routine EASY product instead of starter content", async () => {
  const [page, layout, packageJson, routinesRoute, quantityRoute, completionRoute, storage] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../app/api/routines/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/quantity-completions/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/completions/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../db/storage.ts", import.meta.url), "utf8"),
  ]);

  assert.doesNotMatch(page, /Today’s routines/);
  assert.match(page, /Calendar/);
  assert.match(page, /Add a routine/);
  assert.match(page, /Build my first routine/);
  assert.match(page, /routineez-onboarding-complete/);
  assert.match(page, /SPLASH_DURATION_MS = 2100/);
  assert.match(page, /splash-routine/);
  assert.match(page, /splash-blobs/);
  assert.match(page, /app-background-blobs/);
  assert.match(page, /function BlobCorners/);
  assert.match(page, /splashOverlay/);
  assert.match(page, /SPLASH_FADE_MS = 650/);
  assert.match(page, /splash-blob-purple/);
  assert.match(page, /splash-blob-coral/);
  assert.match(page, /splash-blob-gold/);
  assert.match(page, /splash-blob-sky/);
  assert.match(page, /splash-easy/);
  assert.match(page, /function EasyWord/);
  assert.match(page, /easy-e/);
  assert.match(page, /easy-a/);
  assert.match(page, /easy-s/);
  assert.match(page, /easy-y/);
  assert.match(page, /<span className="easy-a">A<\/span>/);
  assert.match(page, /<span className="easy-s">S<\/span>/);
  assert.match(page, /<span className="easy-y">Y<\/span>/);
  assert.match(page, /window\.clearTimeout\(splashTimer\)/);
  assert.match(page, /Edit routine/);
  assert.match(page, />Edit<\/button>/);
  assert.match(page, /name: form\.get\("name"\)/);
  assert.match(page, /emoji: form\.get\("emoji"\)/);
  assert.match(page, /color: form\.get\("color"\)/);
  assert.match(page, /Daily amount/);
  assert.match(page, /quantity-completions/);
  assert.match(page, /collapsed-progress/);
  assert.match(page, /add-modal-backdrop/);
  assert.match(page, /createPortal\(<div className="add-modal-backdrop"/);
  assert.match(page, /aria-modal="true" aria-label="Add a routine"/);
  assert.doesNotMatch(page, /A new small promise/);
  assert.match(page, /openAddFromHeader/);
  assert.match(page, /function useAnimatedNumber/);
  assert.match(page, /requestAnimationFrame\(animate\)/);
  assert.match(page, /setTimeout\(\(\) =>/);
  assert.match(page, /Different plan by day/);
  assert.match(page, /dayVariant-/);
  assert.doesNotMatch(page, /Your rhythm at a glance/);
  assert.match(page, /edit-modal-backdrop/);
  assert.match(page, /createPortal\(<div className="edit-modal-backdrop"/);
  assert.match(page, /aria-label="Edit routine progress"/);
  assert.match(page, /className="add-modal-stack edit-modal-stack"/);
  assert.match(page, /edit-routine-wizard/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.edit-modal-backdrop \{ z-index: 120/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.edit-form-shell \{ --wizard-accent:[^}]*max-height: 100%;[^}]*overflow: hidden/);
  assert.match(page, /function DeleteRoutineDialog/);
  assert.match(page, /role="alertdialog"/);
  assert.match(page, /Delete routine/);
  assert.match(page, /setRoutineToDelete\(routine\)/);
  assert.doesNotMatch(page, /onDelete=\{\(\) => deleteRoutine\(routine\.id\)\}/);
  assert.match(page, /Active dates/);
  assert.match(page, /name="startDate"/);
  assert.match(page, /name="endDate"/);
  assert.match(page, /function TimeField/);
  assert.match(page, /onClick=\{\(\) => updateTime\(""\)\}/);
  assert.match(page, /routine-live-preview/);
  assert.match(page, /function RoutineLivePreview/);
  assert.doesNotMatch(page, /<RoutineLivePreview/);
  assert.match(page, /Interactive routine preview/);
  assert.match(page, /preview-quantity/);
  assert.match(page, /preview-list/);
  assert.doesNotMatch(page, /filter\(Boolean\)\.slice\(0, 8\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-live-preview \{[^}]*flex: 0 0 auto/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /preview-list \{ overflow: visible; \}/);
  assert.match(page, /\+ Add tracking/);
  assert.match(page, /Named steps to check off/);
  assert.match(page, /Pause and resume one running total/);
  assert.match(page, /Attach a daily progress image/);
  assert.match(page, /function TrackerControl/);
  assert.doesNotMatch(page, /Already included on every routine/);
  assert.match(page, /capture="environment"/);
  assert.match(page, /I avoided this today/);
  assert.match(page, /Enter any amount for the day—there is no goal to reach/);
  assert.doesNotMatch(page, /Record minutes toward a goal/);
  assert.match(page, /value === "" \? 0 : Number\(value\) \|\| 0/);
  assert.doesNotMatch(page, /<button type="submit">Save<\/button>/);
  assert.match(page, /tracker-note-heading/);
  assert.doesNotMatch(page, />Save note<\/button>/);
  assert.match(page, /\.tracking-block input:invalid, \.tracking-block textarea:invalid/);
  assert.doesNotMatch(page, /<small>Live preview<\/small>/);
  assert.match(page, /className="preview-progress" role="progressbar"/);
  assert.doesNotMatch(page, /className="preview-detail-heading"/);
  assert.doesNotMatch(page, /className="quantity-caption"/);
  assert.match(page, /"simple" \| "checklist" \| "quantity" \| "hybrid"/);
  assert.match(page, /const usesChecklist/);
  assert.match(page, /const usesQuantity/);
  assert.match(page, /function TrackingBuilder/);
  assert.match(page, /trackingModeFor\(lists, amounts\)/);
  assert.match(page, /tracking-list-block/);
  assert.match(page, /tracking-amount-block/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /tracking-add-menu \{ position: static/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /step-tone-2 \{ --wizard-accent: var\(--coral\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /setting-card:nth-child\(3n \+ 2\) \{ --setting-accent: var\(--sky\)/);
  assert.match(page, /usesChecklist\(routine\.trackingMode\)[\s\S]*usesQuantity\(routine\.trackingMode\)/);
  assert.match(routinesRoute, /mode === "hybrid"/);
  assert.match(routinesRoute, /function cleanLists/);
  assert.match(routinesRoute, /Add at least one named list with an item/);
  assert.match(routinesRoute, /list_config AS listConfig/);
  assert.match(storage, /list_config TEXT NOT NULL DEFAULT '\[\]'/);
  assert.match(storage, /list_key TEXT NOT NULL DEFAULT 'list-1'/);
  assert.match(quantityRoute, /amount_key AS amountKey|amount_key = \?/);
  assert.match(quantityRoute, /INSERT INTO amount_completions/);
  assert.match(routinesRoute, /amount_config AS amountConfig/);
  assert.match(storage, /CREATE TABLE IF NOT EXISTS amount_completions/);
  assert.match(page, /setPreviewEmoji/);
  assert.match(page, /setPreviewColor/);
  assert.match(page, /function VerticalScrollIndicator/);
  assert.match(page, /setScrollable\(maxScroll > 1\)/);
  assert.match(page, /if \(!scrollable\) return null/);
  assert.match(page, /mutationObserver/);
  assert.match(page, /Scroll \$\{label\}/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /modal-scrollbar::before/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /modal-scroll-thumb::after[\s\S]*width: 5px[\s\S]*background: #6c5ce7/);
  assert.match(page, /picker-scroll/);
  assert.match(page, /function ScrollablePicker/);
  assert.match(page, /Calendar routine filters/);
  assert.match(page, /viewingCurrentMonth/);
  assert.match(page, /calendar-today-button/);
  assert.match(page, /calendar-detail-toolbar/);
  assert.match(page, /calendar-detail-card/);
  assert.match(page, /Days scheduled/);
  assert.match(page, /Routines shown/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.calendar-page-matched \{ display: flex; flex-direction: column; padding-bottom: 88px; overflow: hidden/);
  assert.match(page, /calendar-today-row/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /calendar-today-button \{[^}]*background: var\(--sky\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /@keyframes calendar-today-arrive/);
  assert.match(page, /setMonth\(new Date\(today\.getFullYear\(\), today\.getMonth\(\), 1\)\)/);
  assert.match(page, /calendar-filter-picker/);
  assert.match(page, /scrollClassName="filter-pills"/);
  assert.match(page, /Scroll horizontally for more/);
  assert.doesNotMatch(page, /scroller\.scrollBy|picker-scroll-hint/);
  assert.match(page, /picker-scrollbar/);
  assert.match(page, /scrollFromThumb/);
  assert.match(page, /setPointerCapture/);
  assert.match(page, /Scroll \$\{label\} choices/);
  assert.match(page, /ResizeObserver/);
  assert.match(page, /boundedScroll/);
  assert.match(page, /calc\(\$\{thumb\.left\}% \+ 1px\)/);
  assert.match(page, /keepModalAligned/);
  assert.match(page, /modal\.scrollLeft = 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-thumb::after/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /emoji-picker input, \.color-picker input \{ position: absolute; inset: 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-scrollbar \{[\s\S]*width: 100%; height: 16px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-scrollbar::before \{[\s\S]*height: 3px[\s\S]*transform: translateY\(-50%\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-thumb::after \{[\s\S]*height: 5px[\s\S]*border-radius: 3px[\s\S]*background: #6c5ce7/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.picker-thumb \{[^}]*transition:[^;}]*left/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.picker-scroll \{[^}]*scroll-behavior: auto;[^}]*scroll-snap-type: none/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.emoji-picker label > span/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.color-picker label > span/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.emoji-picker span \{/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.color-picker span \{/);
  assert.match(page, /#8338EC/);
  assert.match(page, /🪥/);
  assert.match(page, /#00A896/);
  assert.match(page, /#212529/);
  assert.match(page, /#CC5DE8/);
  assert.match(page, /🏊/);
  assert.match(page, /🧩/);
  assert.match(page, /👨‍👩‍👧‍👦/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routines-page \{ scrollbar-width: none/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.app-background-blobs \.splash-blob \{ animation-name: app-blob-pop/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.splash-overlay\.leaving \{ visibility: hidden; opacity: 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row\.completed \{ opacity: 1/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /today-page \.routine-list \{[^}]*grid-auto-rows: max-content;[^}]*overflow-y: auto/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row:not\(\.expanded\) \{ height: 110px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row:hover, \.routine-row:active \{ transform: none/);
  assert.match(page, /function DateTile/);
  assert.match(page, /function CalendarNavButton/);
  assert.match(page, /date-nav-icon/);
  assert.match(page, /month: "short"/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /calendar-nav-button\.active \{ position: relative;[\s\S]*background: transparent; border: 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /mobile-wordmark img \{ width: 38px[^}]*drop-shadow\(0 0 13px rgba\(32,34,44/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /mobile-wordmark img \{[^}]*transform: translateY\(2px\)/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /mobile-wordmark img \{[^}]*border:/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav \{[\s\S]*height: 64px;[\s\S]*border-radius: 20px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button\.active::after \{ display: none/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /calendar-page, \.routines-page, \.history-page \{ padding-bottom: 132px/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav::before, \.bottom-nav::after/);
  assert.doesNotMatch(page, /LiquidButton|liquid-glass/);
  assert.match(page, /premium-action/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /Premium actions: solid, polished/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /--brand-spectrum/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /App-icon palette: one coordinated system/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button:nth-child\(1\)\.active[^}]*color: var\(--purple\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button:nth-child\(2\)\.active[^}]*color: var\(--coral\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /grid-template-columns: repeat\(4, 1fr\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button:nth-child\(3\)\.active[^}]*color: #b97a08/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button:nth-child\(4\)\.active[^}]*color: var\(--sky\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.premium-action \{\s*background: var\(--sky\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.easy-e \{ color: var\(--purple\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.easy-a \{ color: var\(--coral\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.easy-s \{ color: var\(--gold\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.easy-y \{ color: var\(--sky\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.history-detail-card \{ padding: 0; border: 0; border-radius: 0; background: transparent; box-shadow: none; \}/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.history-detail-card > header \{ display: grid; justify-items: center;/);
  assert.match(page, /history-page-detail/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.history-page-detail \{ display: flex; flex-direction: column; padding-bottom: 88px; overflow: hidden/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.history-page-detail \.history-day-spacer, \.history-page-detail \.history-day \{ height: clamp\(34px, 5svh, 44px\); aspect-ratio: auto/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.history-legend \{ display: flex; align-items: center; justify-content: center/);
  const monthlyHistory = page.slice(page.indexOf('return <section className="history-detail-card"'), page.indexOf('})() : <section className="history-overview"'));
  assert.doesNotMatch(monthlyHistory, /Completion history|at a glance/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /Calm typography shared by Settings/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.section-title h2, \.calendar-toolbar h2[^}]*font-weight: 600/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.primary-button, \.secondary-button[^}]*font-weight: 650/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /@keyframes routine-reveal/);
  assert.match(page, /CalendarPlus2/);
  assert.match(page, /ChevronLeft/);
  assert.match(page, /day-fill/);
  assert.match(page, /calendar-day \$\{isToday/);
  assert.doesNotMatch(page, /day-dots/);
  assert.doesNotMatch(page, /empty-state-icon[^>]*>☀️/);
  assert.match(page, /mobile-wordmark/);
  assert.match(page, /routineez-checklist\.png/);
  assert.doesNotMatch(page, /src="\/routineez-logo\.png"/);
  assert.doesNotMatch(page, /routineez-mark\.png/);
  assert.match(layout, /routineez-mark\.png/);
  assert.match(page, /mobile-profile/);
  assert.match(page, /className="delete-button"[\s\S]*?<Trash2 aria-hidden="true"/);
  assert.match(page, /Step \{step \+ 1\} of \{steps\.length\}/);
  assert.match(page, /The basics/);
  assert.match(page, /How to track it/);
  assert.match(page, /Make it yours/);
  assert.match(page, /Don’t reuse icons/);
  assert.match(page, /Don’t reuse colors/);
  assert.match(page, /availableEmojis/);
  assert.match(page, /availableColors/);
  assert.match(page, /className="wizard-progress" role="progressbar"/);
  assert.match(page, /stepLockRef\.current/);
  assert.match(page, /disabled=\{saving \|\| stepSettling\}/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /add-form-shell \{[^}]*flex: 1 1 auto; max-height: none; display: flex; overflow: hidden/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /add-modal-stack > \.routine-live-preview \{ max-height: min\(240px, 32svh\)/);
  assert.match(page, /CircleUserRound/);
  assert.match(page, /profile-popover-backdrop/);
  assert.match(page, /profile-settings-button/);
  assert.match(page, /function SettingsPage/);
  assert.match(page, /routineez-preferences/);
  assert.match(page, /timeFormat: "12-hour"/);
  assert.match(page, /formatRoutineTime/);
  assert.match(page, /completed \? 100 : progressParts\.length/);
  assert.match(page, /!expanded && <div className="collapsed-progress"/);
  assert.match(page, /weekStartsOn/);
  assert.match(page, /preferences\.motion === "reduced"/);
  assert.match(page, /Manage routines/);
  assert.match(page, /className="settings-list" role="group" aria-label="Preferences"/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.setting-card \+ \.setting-card \{ border-top:/);
  assert.match(page, /Completed routines/);
  assert.match(page, /Sounds and haptics/);
  assert.match(page, /Get alerts at routine times while Routine EASY is open/);
  assert.match(page, /function DataPrivacyDialog/);
  assert.match(page, /routine-easy-backup-/);
  assert.match(page, /document\.documentElement\.dataset\.theme/);
  assert.match(page, /Notification\.requestPermission/);
  const dataRoute = await readFile(new URL("../app/api/data/route.ts", import.meta.url), "utf8");
  assert.match(dataRoute, /export async function GET/);
  assert.match(dataRoute, /export async function PUT/);
  assert.match(dataRoute, /export async function DELETE/);
  assert.match(dataRoute, /temporaryOwner/);
  assert.match(page, /function TemplateChooser/);
  assert.match(page, /Choose a starting point/);
  assert.match(page, /Start from scratch/);
  assert.match(page, /ROUTINE_TEMPLATES/);
  assert.match(page, /function CompletionHistoryDialog/);
  assert.match(page, /function HistoryPage/);
  assert.match(page, /Day details/);
  assert.match(page, /Edit what was recorded for/);
  assert.match(page, /history-tracker-editor/);
  assert.match(page, /history-summary-fix/);
  assert.doesNotMatch(page, /Correct this day/);
  assert.match(page, /createPortal\(<div className="feature-dialog-backdrop">/);
  assert.match(page, /className="history-edit-sticky"/);
  assert.match(page, /Edit here · auto-saves/);
  assert.match(page, /history-record-row history-record-edit/);
  assert.match(page, /<TrackerControl routine=\{routine\} tracker=\{tracker\}/);
  assert.match(page, /prepareHistoryDetailEdit/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.history-edit-sticky \{ position: sticky/);
  assert.match(page, /History routine filters/);
  assert.match(page, /tab === "history"/);
  assert.match(page, /label="History"/);
  assert.match(page, /history-overview-grid/);
  assert.match(page, /history-title-row/);
  assert.match(page, /buildRoutineHistory/);
  assert.match(page, /Monthly completion/);
  assert.match(page, /history-month-toolbar/);
  assert.match(page, /history-current-month-button/);
  assert.match(page, /This month/);
  assert.match(page, /Skip today/);
  assert.match(page, /Undo skip/);
  assert.match(page, /routine-swipe-surface/);
  assert.match(page, /setPointerCapture/);
  assert.match(page, /Math\.abs\(dragXRef\.current\) >= 70/);
  assert.doesNotMatch(page, /lastSwipeFinishedAtRef/);
  assert.doesNotMatch(page, /performance\.now\(\) - .*< 80/);
  assert.match(page, /const skippedRef = useRef\(skipped\)/);
  assert.match(page, /const nextSkipped = !skippedRef\.current/);
  assert.match(page, /onSkip\(nextSkipped\)/);
  assert.match(page, /routineMutationQueuesRef/);
  assert.match(page, /function queueRoutineMutation/);
  assert.match(page, /const previous = queues\.get\(routineId\) \?\? Promise\.resolve\(\)/);
  assert.match(page, /await setRoutineSkip\(routine\.id, false, date\)/);
  assert.match(page, /completionsRef\.current/);
  assert.doesNotMatch(page, /suppressClickRef/);
  assert.match(page, /role="button" tabIndex=\{0\}/);
  assert.match(page, /onPointerCancel=\{cancelSwipe\}/);
  assert.match(page, /const tapGesture = gestureAxis === "pending"/);
  assert.match(page, /Math\.abs\(dragXRef\.current\) < 18/);
  assert.match(page, /event\.key === "Enter" \|\| event\.key === " "/);
  assert.match(page, /function undoRoutineSkip/);
  assert.match(page, /className="routine-check-zone"/);
  assert.match(page, /const checkPointerRef = useRef/);
  assert.match(page, /onPointerDown=\{beginCheckPointer\}/);
  assert.match(page, /onPointerUp=\{finishCheckPointer\}/);
  assert.match(page, /distance < 22/);
  assert.doesNotMatch(page, /className="routine-check-zone" onClick=/);
  assert.match(page, /if \(skippedRef\.current\) toggleSkip\(\)/);
  assert.match(page, /else if \(hasDetails\) setExpanded/);
  assert.match(page, /Tap anywhere or swipe left or right to undo skip/);
  assert.match(page, /setAmount\(routine\.id, amount, 0, date, false\)/);
  assert.match(page, /aria-description=\{skipped/);
  assert.doesNotMatch(page, /className="skip-today-button"/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row\.skipped \.collapsed-progress span \{ width: 100% !important/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-swipe-underlay/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row\.skipped \{ border-style: dashed/);
  assert.match(page, /Duplicate/);
  const duplicateRoutineSource = page.slice(page.indexOf("function duplicateRoutine"), page.indexOf("async function deleteRoutine"));
  assert.match(duplicateRoutineSource, /setSelectedTemplate\(\{/);
  assert.match(duplicateRoutineSource, /setShowAdd\(true\)/);
  assert.doesNotMatch(duplicateRoutineSource, /fetch\(/);
  assert.match(page, /Save duplicate/);
  assert.match(completionRoute, /"completed" \| "skipped"/);
  assert.match(completionRoute, /ON CONFLICT\(owner_key, routine_id, date\) DO UPDATE SET status/);
  assert.match(routinesRoute, /routine_id AS routineId, date, status FROM completions/);
  assert.doesNotMatch(routinesRoute, /const defaults =|Morning vitamins|Warm up.*Main workout.*Cool down/s);
  assert.match(storage, /status TEXT NOT NULL DEFAULT 'completed'/);
  assert.doesNotMatch(page, /today-date-copy|date-balance/);
  assert.match(page, /item-completions/);
  assert.match(layout, /Routine EASY — Simple Routine Tracker/);
  assert.match(layout, /themeInitializationScript/);
  assert.match(layout, /routineez-preferences/);
  assert.match(layout, /suppressHydrationWarning/);
  assert.match(layout, /window\.matchMedia\("\(prefers-color-scheme: dark\)"\)/);
  assert.match(page, /if \(!preferencesLoaded\) return/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.splash-blob > i::after/);
  assert.doesNotMatch(page, /SkeletonPreview|codex-preview/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
});

test("dark mode covers mobile cards and interactive surfaces", async () => {
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");

  assert.match(css, /Dark theme completion pass/);
  assert.match(css, /html\[data-theme="dark"\] \.progress-card \{[^}]*background: linear-gradient/);
  assert.match(css, /html\[data-theme="dark"\] :is\(\.check-circle, \.preview-check, \.preview-list button > span\)/);
  assert.match(css, /html\[data-theme="dark"\] \.bottom-nav \.date-nav-icon \{ background: #211e26/);
  assert.match(css, /html\[data-theme="dark"\] \.history-day \{ color: #aaa6b1; background: #211e26/);
  assert.match(css, /html\[data-theme="dark"\] :is\(\.tracking-block, \.tracking-add-menu > button:hover, \.choice-toggle:hover\)/);
  assert.match(css, /html\[data-theme="dark"\] \.filter-pills button\.active \{[^}]*background: var\(--pill\)/);
  assert.match(css, /html\[data-theme="dark"\] \.routine-card-actions button \{[^}]*background: color-mix/);
  assert.match(css, /html\[data-theme="dark"\] \.delete-button,/);
  assert.match(css, /Mobile navigation is a set of floating pods/);
  assert.match(css, /\.bottom-nav \{\s*height: 68px;\s*gap: 7px;[\s\S]*?background: transparent;/);
  assert.match(css, /\.bottom-nav button\.active,[\s\S]*?transform: translateY\(-7px\)/);
  assert.match(css, /html\[data-theme="dark"\] \.bottom-nav button\.active,[\s\S]*?background: color-mix/);
});
