import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships the RoutineEZ product instead of starter content", async () => {
  const [page, layout, packageJson] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);

  assert.match(page, /Today’s routines/);
  assert.match(page, /Calendar/);
  assert.match(page, /Add a routine/);
  assert.match(page, /Build my first routine/);
  assert.match(page, /routineez-onboarding-complete/);
  assert.match(page, /Routine options/);
  assert.match(page, /Daily amount/);
  assert.match(page, /quantity-completions/);
  assert.match(page, /collapsed-progress/);
  assert.match(page, /add-modal-backdrop/);
  assert.match(page, /aria-modal="true" aria-label="Add a routine"/);
  assert.doesNotMatch(page, /A new small promise/);
  assert.match(page, /openAddFromHeader/);
  assert.match(page, /function useAnimatedNumber/);
  assert.match(page, /requestAnimationFrame\(animate\)/);
  assert.match(page, /setTimeout\(\(\) =>/);
  assert.match(page, /Different plan by day/);
  assert.match(page, /dayVariant-/);
  assert.doesNotMatch(page, /Your rhythm at a glance/);
  assert.match(page, /edit-modal-backdrop/);
  assert.match(page, /Active dates/);
  assert.match(page, /name="startDate"/);
  assert.match(page, /name="endDate"/);
  assert.match(page, /function TimeField/);
  assert.match(page, /onClick=\{\(\) => setTime\(""\)\}/);
  assert.match(page, /picker-scroll/);
  assert.match(page, /function ScrollablePicker/);
  assert.match(page, /Scroll horizontally for more/);
  assert.doesNotMatch(page, /scroller\.scrollBy|picker-scroll-hint/);
  assert.match(page, /picker-scrollbar/);
  assert.match(page, /scrollFromThumb/);
  assert.match(page, /setPointerCapture/);
  assert.match(page, /Scroll \$\{label\} choices/);
  assert.match(page, /ResizeObserver/);
  assert.match(page, /boundedScroll/);
  assert.match(page, /calc\(\$\{thumb\.left\}% \+ 1px\)/);
  assert.match(page, /keepModalAligned/);
  assert.match(page, /modal\.scrollLeft = 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-thumb::after/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /emoji-picker input, \.color-picker input \{ position: absolute; inset: 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-scrollbar \{[\s\S]*width: 100%; height: 16px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-scrollbar::before \{[\s\S]*height: 3px[\s\S]*transform: translateY\(-50%\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-thumb::after \{[\s\S]*height: 5px[\s\S]*border-radius: 3px[\s\S]*background: #6c5ce7/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.picker-thumb \{[^}]*transition:[^;}]*left/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.emoji-picker label > span/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.color-picker label > span/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.emoji-picker span \{/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.color-picker span \{/);
  assert.match(page, /#8338EC/);
  assert.match(page, /🪥/);
  assert.match(page, /#00A896/);
  assert.match(page, /#212529/);
  assert.match(page, /#CC5DE8/);
  assert.match(page, /🏊/);
  assert.match(page, /🧩/);
  assert.match(page, /👨‍👩‍👧‍👦/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routines-page \{ scrollbar-width: none/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /radial-gradient\(circle at -36px 145px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row\.completed \{ opacity: 1/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row:hover, \.routine-row:active \{ transform: none/);
  assert.match(page, /function DateTile/);
  assert.match(page, /function CalendarNavButton/);
  assert.match(page, /date-nav-icon/);
  assert.match(page, /month: "short"/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /calendar-nav-button\.active \{ position: relative;[\s\S]*background: transparent; border: 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav \{[\s\S]*height: 64px;[\s\S]*border-radius: 20px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button\.active::after \{ display: none/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routines-page \{ padding-bottom: 132px/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav::before, \.bottom-nav::after/);
  assert.doesNotMatch(page, /LiquidButton|liquid-glass/);
  assert.match(page, /premium-action/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /Premium actions: solid, polished/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /@keyframes routine-reveal/);
  assert.match(page, /CalendarPlus2/);
  assert.match(page, /ChevronLeft/);
  assert.match(page, /day-fill/);
  assert.match(page, /selected-routine-day/);
  assert.doesNotMatch(page, /day-dots/);
  assert.doesNotMatch(page, /empty-state-icon[^>]*>☀️/);
  assert.match(page, /mobile-wordmark/);
  assert.match(page, /mobile-header-spacer/);
  assert.doesNotMatch(page, /today-date-copy|date-balance/);
  assert.match(page, /item-completions/);
  assert.match(layout, /RoutineEZ — Simple Routine Tracker/);
  assert.doesNotMatch(page, /SkeletonPreview|codex-preview/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
});
