import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships the RoutineEZ product instead of starter content", async () => {
  const [page, layout, packageJson, routinesRoute, quantityRoute, completionRoute, storage] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../app/api/routines/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/quantity-completions/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/completions/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../db/storage.ts", import.meta.url), "utf8"),
  ]);

  assert.doesNotMatch(page, /Today’s routines/);
  assert.match(page, /Calendar/);
  assert.match(page, /Add a routine/);
  assert.match(page, /Build my first routine/);
  assert.match(page, /routineez-onboarding-complete/);
  assert.match(page, /SPLASH_DURATION_MS = 2100/);
  assert.match(page, /splash-routine/);
  assert.match(page, /splash-ez/);
  assert.match(page, /window\.clearTimeout\(splashTimer\)/);
  assert.match(page, /Edit routine/);
  assert.match(page, />Edit<\/button>/);
  assert.match(page, /name: form\.get\("name"\)/);
  assert.match(page, /emoji: form\.get\("emoji"\)/);
  assert.match(page, /color: form\.get\("color"\)/);
  assert.match(page, /Daily amount/);
  assert.match(page, /quantity-completions/);
  assert.match(page, /collapsed-progress/);
  assert.match(page, /add-modal-backdrop/);
  assert.match(page, /aria-modal="true" aria-label="Add a routine"/);
  assert.doesNotMatch(page, /A new small promise/);
  assert.match(page, /openAddFromHeader/);
  assert.match(page, /function useAnimatedNumber/);
  assert.match(page, /requestAnimationFrame\(animate\)/);
  assert.match(page, /setTimeout\(\(\) =>/);
  assert.match(page, /Different plan by day/);
  assert.match(page, /dayVariant-/);
  assert.doesNotMatch(page, /Your rhythm at a glance/);
  assert.match(page, /edit-modal-backdrop/);
  assert.match(page, /function DeleteRoutineDialog/);
  assert.match(page, /role="alertdialog"/);
  assert.match(page, /Delete routine/);
  assert.match(page, /setRoutineToDelete\(routine\)/);
  assert.doesNotMatch(page, /onDelete=\{\(\) => deleteRoutine\(routine\.id\)\}/);
  assert.match(page, /Active dates/);
  assert.match(page, /name="startDate"/);
  assert.match(page, /name="endDate"/);
  assert.match(page, /function TimeField/);
  assert.match(page, /onClick=\{\(\) => updateTime\(""\)\}/);
  assert.match(page, /routine-live-preview/);
  assert.match(page, /function RoutineLivePreview/);
  assert.doesNotMatch(page, /<RoutineLivePreview/);
  assert.match(page, /Interactive routine preview/);
  assert.match(page, /preview-quantity/);
  assert.match(page, /preview-list/);
  assert.doesNotMatch(page, /filter\(Boolean\)\.slice\(0, 8\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-live-preview \{[^}]*flex: 0 0 auto/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /preview-list \{ overflow: visible; \}/);
  assert.match(page, /\+ Add tracking/);
  assert.match(page, /Named steps to check off/);
  assert.match(page, /A named numbered tracker/);
  assert.match(page, /className="quantity-name"/);
  assert.match(page, /\.tracking-block input:invalid, \.tracking-block textarea:invalid/);
  assert.doesNotMatch(page, /<small>Live preview<\/small>/);
  assert.match(page, /className="preview-progress" role="progressbar"/);
  assert.doesNotMatch(page, /className="preview-detail-heading"/);
  assert.doesNotMatch(page, /className="quantity-caption"/);
  assert.match(page, /"simple" \| "checklist" \| "quantity" \| "hybrid"/);
  assert.match(page, /const usesChecklist/);
  assert.match(page, /const usesQuantity/);
  assert.match(page, /function TrackingBuilder/);
  assert.match(page, /trackingModeFor\(lists, amounts\)/);
  assert.match(page, /tracking-list-block/);
  assert.match(page, /tracking-amount-block/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /tracking-add-menu \{ position: static/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /step-tone-2 \{ --wizard-accent: var\(--coral\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /setting-card:nth-child\(3n \+ 2\) \{ --setting-accent: var\(--sky\)/);
  assert.match(page, /usesChecklist\(routine\.trackingMode\)[\s\S]*usesQuantity\(routine\.trackingMode\)/);
  assert.match(routinesRoute, /mode === "hybrid"/);
  assert.match(routinesRoute, /function cleanLists/);
  assert.match(routinesRoute, /Add at least one named list with an item/);
  assert.match(routinesRoute, /list_config AS listConfig/);
  assert.match(storage, /list_config TEXT NOT NULL DEFAULT '\[\]'/);
  assert.match(storage, /list_key TEXT NOT NULL DEFAULT 'list-1'/);
  assert.match(quantityRoute, /amount_key AS amountKey|amount_key = \?/);
  assert.match(quantityRoute, /INSERT INTO amount_completions/);
  assert.match(routinesRoute, /amount_config AS amountConfig/);
  assert.match(storage, /CREATE TABLE IF NOT EXISTS amount_completions/);
  assert.match(page, /setPreviewEmoji/);
  assert.match(page, /setPreviewColor/);
  assert.match(page, /function VerticalScrollIndicator/);
  assert.match(page, /setScrollable\(maxScroll > 1\)/);
  assert.match(page, /if \(!scrollable\) return null/);
  assert.match(page, /mutationObserver/);
  assert.match(page, /Scroll \$\{label\}/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /modal-scrollbar::before/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /modal-scroll-thumb::after[\s\S]*width: 5px[\s\S]*background: #6c5ce7/);
  assert.match(page, /picker-scroll/);
  assert.match(page, /function ScrollablePicker/);
  assert.match(page, /Calendar routine filters/);
  assert.match(page, /viewingCurrentMonth/);
  assert.match(page, /calendar-today-button/);
  assert.match(page, /setMonth\(new Date\(today\.getFullYear\(\), today\.getMonth\(\), 1\)\)/);
  assert.match(page, /calendar-filter-picker/);
  assert.match(page, /scrollClassName="filter-pills"/);
  assert.match(page, /Scroll horizontally for more/);
  assert.doesNotMatch(page, /scroller\.scrollBy|picker-scroll-hint/);
  assert.match(page, /picker-scrollbar/);
  assert.match(page, /scrollFromThumb/);
  assert.match(page, /setPointerCapture/);
  assert.match(page, /Scroll \$\{label\} choices/);
  assert.match(page, /ResizeObserver/);
  assert.match(page, /boundedScroll/);
  assert.match(page, /calc\(\$\{thumb\.left\}% \+ 1px\)/);
  assert.match(page, /keepModalAligned/);
  assert.match(page, /modal\.scrollLeft = 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-thumb::after/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /emoji-picker input, \.color-picker input \{ position: absolute; inset: 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-scrollbar \{[\s\S]*width: 100%; height: 16px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-scrollbar::before \{[\s\S]*height: 3px[\s\S]*transform: translateY\(-50%\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /picker-thumb::after \{[\s\S]*height: 5px[\s\S]*border-radius: 3px[\s\S]*background: #6c5ce7/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.picker-thumb \{[^}]*transition:[^;}]*left/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.picker-scroll \{[^}]*scroll-behavior: auto;[^}]*scroll-snap-type: none/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.emoji-picker label > span/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.color-picker label > span/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.emoji-picker span \{/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.color-picker span \{/);
  assert.match(page, /#8338EC/);
  assert.match(page, /🪥/);
  assert.match(page, /#00A896/);
  assert.match(page, /#212529/);
  assert.match(page, /#CC5DE8/);
  assert.match(page, /🏊/);
  assert.match(page, /🧩/);
  assert.match(page, /👨‍👩‍👧‍👦/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routines-page \{ scrollbar-width: none/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /radial-gradient\(circle at -36px 145px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row\.completed \{ opacity: 1/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /today-page \.routine-list \{[^}]*grid-auto-rows: max-content;[^}]*overflow-y: auto/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row:not\(\.expanded\) \{ height: 110px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /routine-row:hover, \.routine-row:active \{ transform: none/);
  assert.match(page, /function DateTile/);
  assert.match(page, /function CalendarNavButton/);
  assert.match(page, /date-nav-icon/);
  assert.match(page, /month: "short"/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /calendar-nav-button\.active \{ position: relative;[\s\S]*background: transparent; border: 0/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /mobile-wordmark img \{ width: 38px[^}]*drop-shadow\(0 0 13px rgba\(32,34,44/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /mobile-wordmark img \{[^}]*transform: translateY\(2px\)/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /mobile-wordmark img \{[^}]*border:/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav \{[\s\S]*height: 64px;[\s\S]*border-radius: 20px/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button\.active::after \{ display: none/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /calendar-page, \.routines-page, \.history-page \{ padding-bottom: 132px/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav::before, \.bottom-nav::after/);
  assert.doesNotMatch(page, /LiquidButton|liquid-glass/);
  assert.match(page, /premium-action/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /Premium actions: solid, polished/);
  assert.doesNotMatch(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /--brand-spectrum/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /App-icon palette: one coordinated system/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button:nth-child\(2\)\.active[^}]*color: var\(--sky\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /grid-template-columns: repeat\(4, 1fr\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /bottom-nav button:nth-child\(4\)\.active[^}]*color: var\(--mint\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.premium-action \{\s*background: var\(--sky\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.brand-e \{ color: var\(--sky\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.brand-z \{ color: var\(--coral\)/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /Calm typography shared by Settings/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.section-title h2, \.calendar-toolbar h2[^}]*font-weight: 600/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /\.primary-button, \.secondary-button[^}]*font-weight: 650/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /@keyframes routine-reveal/);
  assert.match(page, /CalendarPlus2/);
  assert.match(page, /ChevronLeft/);
  assert.match(page, /day-fill/);
  assert.match(page, /selected-routine-day/);
  assert.doesNotMatch(page, /day-dots/);
  assert.doesNotMatch(page, /empty-state-icon[^>]*>☀️/);
  assert.match(page, /mobile-wordmark/);
  assert.match(page, /routineez-checklist\.png/);
  assert.doesNotMatch(page, /src="\/routineez-logo\.png"/);
  assert.doesNotMatch(page, /routineez-mark\.png/);
  assert.match(layout, /routineez-logo\.png/);
  assert.match(page, /mobile-profile/);
  assert.match(page, /className="delete-button"[\s\S]*?<Trash2 aria-hidden="true"/);
  assert.match(page, /Step \{step \+ 1\} of \{steps\.length\}/);
  assert.match(page, /The basics/);
  assert.match(page, /How to track it/);
  assert.match(page, /Make it yours/);
  assert.match(page, /Don’t reuse icons/);
  assert.match(page, /Don’t reuse colors/);
  assert.match(page, /availableEmojis/);
  assert.match(page, /availableColors/);
  assert.match(page, /className="wizard-progress" role="progressbar"/);
  assert.match(page, /stepLockRef\.current/);
  assert.match(page, /disabled=\{saving \|\| stepSettling\}/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /add-form-shell \{[^}]*flex: 1 1 auto; max-height: none; display: flex; overflow: hidden/);
  assert.match(await readFile(new URL("../app/globals.css", import.meta.url), "utf8"), /add-modal-stack > \.routine-live-preview \{ max-height: min\(240px, 32svh\)/);
  assert.match(page, /CircleUserRound/);
  assert.match(page, /profile-popover-backdrop/);
  assert.match(page, /profile-settings-button/);
  assert.match(page, /function SettingsPage/);
  assert.match(page, /routineez-preferences/);
  assert.match(page, /timeFormat: "12-hour"/);
  assert.match(page, /formatRoutineTime/);
  assert.match(page, /completed \? 100 : 0/);
  assert.match(page, /!expanded && <div className="collapsed-progress"/);
  assert.match(page, /weekStartsOn/);
  assert.match(page, /preferences\.motion === "reduced"/);
  assert.match(page, /Manage routines/);
  assert.match(page, /function TemplateChooser/);
  assert.match(page, /Choose a starting point/);
  assert.match(page, /Start from scratch/);
  assert.match(page, /ROUTINE_TEMPLATES/);
  assert.match(page, /function CompletionHistoryDialog/);
  assert.match(page, /function HistoryPage/);
  assert.match(page, /History routine filters/);
  assert.match(page, /tab === "history"/);
  assert.match(page, /label="History"/);
  assert.match(page, /history-overview-grid/);
  assert.match(page, /buildRoutineHistory/);
  assert.match(page, /Last 30 days/);
  assert.match(page, /Skip today/);
  assert.match(page, /Undo skip/);
  assert.match(page, /Duplicate/);
  assert.match(page, /setEditingRoutineId\(data\.routine\.id\)/);
  assert.match(completionRoute, /"completed" \| "skipped"/);
  assert.match(completionRoute, /ON CONFLICT\(owner_key, routine_id, date\) DO UPDATE SET status/);
  assert.match(routinesRoute, /routine_id AS routineId, date, status FROM completions/);
  assert.match(storage, /status TEXT NOT NULL DEFAULT 'completed'/);
  assert.doesNotMatch(page, /today-date-copy|date-balance/);
  assert.match(page, /item-completions/);
  assert.match(layout, /RoutineEZ — Simple Routine Tracker/);
  assert.doesNotMatch(page, /SkeletonPreview|codex-preview/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
});
